version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: entra_postgres
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgrest:
    image: postgrest/postgrest:v12.2.5
    container_name: entra_postgrest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.postgrest
    ports:
      - "3000:3000"

  n8n:
    image: n8nio/n8n:latest
    container_name: entra_n8n
    depends_on:
      - postgres
      - postgrest
    env_file:
      - .env.n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  pgdata:
  n8n_data:
